server:
  tomcat:
    accept-count: 10
    threads:
      max: 300
    connection-timeout: 10000
    
item:
  insert:
    thread:
      name-prefix: ITEM-INSERT-
      core-pool-size: 3
      max-pool-size: 20
      queue-capacity: 20

logging:
  file:
    name: logs/api-local3.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.item: debug
    
spring:
  config:
    import:
      - classpath:/config/datasource-local.yml
      - classpath:/config/activemq-local.yml
      - classpath:/config/kafka-local.yml
        
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    
token:
  expiration_time: 86400000
  secret: SECU100

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        permittedNumberOfCallsInHalfOpenState: 4
        maxWaitDurationInHalfOpenState: 0
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
    instances:
      itemCircuitBreaker:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 5000
    instances:
      insertItem:
        baseConfig: default
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 1
    instances:
      bulkInsertItem:
        baseConfig: default
        